%% From lecture Notes
function [ R02 ] = R02RRR(theta)

    theta1 = theta(1);
    theta2 = theta(2);

    R01 =   [...
           cos(theta1)  -sin(theta1)  0 ;...
           sin(theta1)   cos(theta1)  0 ;...
                0              0      1 ;...
    ];

    R12 =   [...
           cos(theta2)  -sin(theta2)  0 ;...
           sin(theta2)   cos(theta2)  0 ;...
                0              0      1 ;...
    ];

    R02 = R01*R12;

end

