%% From lecture Notes
function [ R3 ] = R3RRR(theta3)

    R3 =   [...
           cos(theta3)  -sin(theta3)  0 ;...
           sin(theta3)   cos(theta3)  0 ;...
                0              0      1 ;...
    ];

end

