%% From lecture Notes
function [ R36 ] = R36SF(theta4,theta5,theta6)

    R34 =   [...
           cos(theta4)  -sin(theta4)  0 ;...
           sin(theta4)   cos(theta4)  0 ;...
                0              0      1 ;...
    ];

    R45 =   [...
            cos(theta5)  -sin(theta5)  0 ;...
                 0              0      1 ;...
           -sin(theta5)  -cos(theta5)  0 ;...
    ];

    R56 =   [...
            cos(theta6)  -sin(theta6)  0 ;...
                 0              0     -1 ;...
            sin(theta6)   cos(theta6)  0 ;...
    ];

    R36 = R34*R45*R56;

end

