
syms q1 q2 q1dot q2dot V

m =    [...
        (theta1+theta2*sin(q2)^2)  ,  (theta3*cos(q2))  ;...
            (theta3*cos(q2))       ,     (theta2)       ;...
];


c =    [...
             (2*theta2*cos(q2)*q2dot      ,  (-theta3*sin(q2)*q2dot)  ;...
         (-theta2*sin(q2)*cos(q2)*q1dot)  ,              0            ;...
];


f =    [...
         theta5*q1dot ;...
         theta6*q2dot ;...
];

g =    [...
                  0       ;...
        -theta4*g*sin(q2) ;...
];

v =    [...
        V  ;...
        0  ;...
];

qdoubledot = -m\(c*[q1dot;q2dot]+f+g-v);
